== 14 Testing
=== 14.3 Conventional testing

https://github.com/lukleh/haskell-book-exercises/tree/gh-pages/ch14/addition

[source]
----
include::addition/Addition.hs[]
----

=== 14.5 Morse code

https://github.com/lukleh/haskell-book-exercises/tree/gh-pages/ch14/morsecode

[source]
----
include::morsecode/test/Spec.hs[]
----
I have `morsecode` instead of `morse` and loadding tests is `stack ghci morsecode:morsecode-test`

=== 14.7 Chapter Exercises
==== Validating numbers into words
https://github.com/lukleh/haskell-book-exercises/tree/gh-pages/ch14/wordnumber

[source]
----
include::wordnumber/test/Spec.hs[]
----

==== Using QuickCheck
CAUTION: had to use `Test.QuickCheck.Function` in point 8 to make it work

Run tests: `stack test`

. propHalf `pass:[+++] OK, passed 100 tests.`
. propSort `pass:[+++] OK, passed 100 tests.`
. plusAssociative `pass:[+++] OK, passed 100 tests.`
+
plusCommutative `pass:[+++] OK, passed 100 tests.`
. multiAssociative `pass:[+++] OK, passed 100 tests.`
+
multiCommutative `pass:[+++] OK, passed 100 tests.`
. propQuotRem `pass:[+++] OK, passed 100 tests.`
+
propDivMod `pass:[+++] OK, passed 100 tests.`
. powerAssociative 
+
....
*** Failed! Falsifiable (after 1 test):
0
0
0
....
+
powerCommutative
+
....
*** Failed! Falsifiable (after 2 tests):                  
1
0
....
. propReverse `pass:[+++] OK, passed 100 tests.`
. applyProp `pass:[+++] OK, passed 100 tests.`
+
composeProp `pass:[+++] OK, passed 100 tests.`
. inConcatProp 
+
....
*** Failed! Falsifiable (after 2 tests and 2 shrinks):    
"a"
"b"
....
+
concatProp `pass:[+++] OK, passed 100 tests.`
. lenTakeProb 
+
....
*** Failed! Falsifiable (after 3 tests and 1 shrink):     
2
""
....
. idProp `pass:[+++] OK, passed 100 tests.`


https://github.com/lukleh/haskell-book-exercises/tree/gh-pages/ch14/usingquickcheck

[source]
----
include::usingquickcheck/test/Spec.hs[]
----

==== Failure
Floating point precission cannot guarantee equality
[source]
----
include::ch14_14.7_failure.hs[]
----
....
*Main> main 
*** Failed! Falsifiable (after 2 tests and 1037 shrinks):     
2.225078033262077e-308
....

==== Idempotence

[source]
----
include::ch14_14.7_indepotence.hs[]
----
....
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
....

==== Make a Gen random generator for the datatype

[source]
----
include::ch14_14.7_1.hs[]
----

==== Hangman testing
WARNING: not done, will have to come back to this later
[source]
----
include::ch14_14.7_hangman.hs[]
----

==== Validating ciphers
WARNING: need to do proper generators
[source]
----
include::ch14_14.7_2.hs[]
----