== 13 Building projects in Haskell

Files at https://github.com/lukleh/haskell-book-exercises/tree/gh-pages/ch13

https://github.com/commercialhaskell/stack/blob/master/doc/faq.md

https://github.com/commercialhaskell/stack/blob/master/doc/GUIDE.md

http://docs.haskellstack.org/en/stable/README.html

==== Differences between cabal and stack
. `stack new proj` instead of `mkdir proj; cd proj; cabal init`
. `stack` creates `Lib` automatically
. `cabal sandbox init` no need
. `stack build`
. `stack exec proj-exe`
. `stack ghci` or `stack repl` - they appear to be identical

=== 13.3 Working with a basic project
All the changes over the whole chapter at https://github.com/lukleh/haskell-book-exercises/tree/gh-pages/ch13/hello

=== 13.7 More on importing modules
==== Intermission: Check your understanding
. `forever` and `when`
. all the import without `qualified` keyword
. everything exported in `Database.Blacktip.Types`
. details
.. just look for what is after the `as` keyword in the imports
.. `Filesystem`
.. `Control.Monad`

=== 13.9 do syntax and IO

. error as expected
+
[source]
----
include::ch13_13.9_0.hs[]
----
. consumes two characters and prints `True` or `False`
+
[source]
----
include::ch13_13.9_1.hs[]
----
. consumes two characters and prints `True` if true, or nothing.
+
[source]
----
include::ch13_13.9_2.hs[]
----

=== 13.15 Chapter exercises

==== Hangman game logic
Sources at https://github.com/lukleh/haskell-book-exercises/tree/gh-pages/ch13/hangman

To count only incorrect guesses, I have modified `gameOver` condition to `if (length guessed - length (filter isJust discovered)) > 7 then`

==== Modifying code
. Caesar and Vigenere cyphers taking input from user
+
[source]
----
include::ch13_13.15_1.hs[]
----
+
[source]
----
include::ch13_13.15_0.hs[]
----
. using `exitSuccess` in palindrome
+
[source]
----
include::ch13_13.15_2.hs[]
----
. palindrome on sentences
+
WARNING: not sure I get the assignment other than using `toLower`
+
[source]
----
include::ch13_13.15_3.hs[]
----
. `gimmePerson`
+
[source]
----
include::ch13_13.15_4.hs[]
----