== 16 Functor
=== 116.4 Let’s talk about f , baby
==== Intermission: Exercises
because kind of `(->)` is `(->) pass:[::] pass:[*] -> pass:[*] -> pass:[*]` the following is

. kind of `a` if `*`
. `b` has kind `pass:[*] -> pass:[*]`, `T` has kind `pass:[*] -> pass:[*]`
. `c` has kind `pass:[*] -> pass:[*] -> pass:[*]`

=== 16.7 Commonly used functors
==== The functors are stacked and that’s a fact
little write out of what happens when we compose functors

....
replaceWithP = const 'p'

:t replaceWithP 
replaceWithP :: b -> Char

lms = [Just "Ave", Nothing, Just "woohoo"]

now we try try to this:
(fmap . fmap) replaceWithP lms
and the result is:
[Just 'p',Nothing,Just 'p']

let's disect this:

:t (fmap . fmap)
(Functor f, Functor f1) => (a -> b) -> f (f1 a) -> f (f1 b)

fmap :: Functor f => (m -> n) -> f m -> f n

fmap :: Functor g => (x -> y) -> g x -> g y


(x -> y) -> g x -> g y  
apply: replaceWithP :: b -> Char
result is:
g b -> g Char
that is (b -> Char) substitued in (g x -> g y)

(m -> n) -> f m -> f n
apply: (g b -> g Char)
result is:
f (g b) -> f (g Char)
that is (b -> Char) substitued in (f m -> f n)


f (g b) -> f (g Char)
apply: lms
result is:
f unwraps the list
g unwraps the Maybe
replaceWithP is applied to the value

voilà, it does work as advertised :)

three compositions go one more level deeper
(fmap . fmap . fmap)
as we can also fmap over String 
....

==== One more round for the P-Funkshun
[source]
----
include::ch16_16.7_0.hs[]
----

==== Intermission: Lifting Exercises
. `a = fmap (+1) (read "[1]" :: [Int])`
. `b = (fmap . fmap) (++ "lol") (Just ["Hi,", "Hello"])`
. `c = fmap (*2) (\x -> x - 2)` also `c = (*2) . (\x -> x - 2)`
. `d = fmap ((return '1' ++) . show) (\x -> [x, 1..3])`
+
also `d = ((return '1' ++) . show) . (\x -> [x, 1..3])`
+
and without `return` that I do not undestand here
+
`d = fmap (("1" ++) . show) (\x -> [x, 1..3])`
. `e`
+
WARNING: WTF? have no clue

=== 16.10 Intermission: Exercises
. `newtype Identity a = Identity a`
+
[source]
----
include::ch16_16.10_1.hs[]
----
. `data Pair a = Pair a a`
+
[source]
----
include::ch16_16.10_2.hs[]
----
. `data Two a b = Two a b`
+
[source]
----
include::ch16_16.10_3.hs[]
----
. `data Three a b c = Three a b c`
+
[source]
----
include::ch16_16.10_4.hs[]
----
. `data Three' a b = Three' a b b`
+
[source]
----
include::ch16_16.10_5.hs[]
----
. `data Four a b c d = Four a b c d`
+
[source]
----
include::ch16_16.10_6.hs[]
----
. `data Four' a b = Four' a a a b`
+
[source]
----
include::ch16_16.10_7.hs[]
----
. `data Trivial = Trivial` has kind `*`, cannot be Functor

=== 16.11 Ignoring possibilities
==== Maybe - Short Exercise
[source]
----
include::ch16_16.11_1.hs[]
----

==== Either - Short Exercise
. `Functor` for `Either` like type
+
[source]
----
include::ch16_16.11_2.hs[]
----
. Either has kind * -> * -> * , you cannot apply "second" argument first to get kind * -> *

=== 16.17 Chapter exercises
==== Is valid Functor

. no, kind `*`
. yes, kind `* -> *`
. yes, kind `* -> *`, similar to `Maybe`
. yes, `Mu f` kind is `* -> *`, but making it Functor instance is kinda funky.
. no, `data D =....` not a `* -> *`

==== Rearrange the arguments

. flip `a` and `b` in the `Sum`
+
[source]
----
include::ch16_16.17_1.hs[]
----
. flip `b` and `c` in the `Company`
+
[source]
----
include::ch16_16.17_2.hs[]
----
. flip `a` and `b` in the `More`
+
[source]
----
include::ch16_16.17_3.hs[]
----

==== Write Functor instances
. `data Quant a b`
+
[source]
----
include::ch16_16.17_4.hs[]
----
. simillar to `Constant` in the 16.12 chapter
+
[source]
----
include::ch16_16.17_5.hs[]
----
. `Flip` from earlier
+
[source]
----
include::ch16_16.17_6.hs[]
----
. `EvilGoateeConst`
+
[source]
----
include::ch16_16.17_7.hs[]
----
. virtually identical to `Wrap` earlier, `f` in `LiftItOut f a` needs to be `Functor` to make sense at all
+
[source]
----
include::ch16_16.17_8.hs[]
----
. double fmap wrap
+
[source]
----
include::ch16_16.17_9.hs[]
----
. `IgnoreOne`
+
[source]
----
include::ch16_16.17_10.hs[]
----
. `Notorious`
+
[source]
----
include::ch16_16.17_11.hs[]
----
. `List`
+
[source]
----
include::ch16_16.17_12.hs[]
----
. triple deep
+
[source]
----
include::ch16_16.17_13.hs[]
----
. looks right, but not sure
+
[source]
----
include::ch16_16.17_14.hs[]
----